### ISSUE TITLE
Add `DicePools` named range to character sheets

### ISSUE THREAD

**Issue by Alan19** [Alan19/TwoDee#59]
I would prefer the format the format 
`Name | Pool`
@belathus

**Comment by belathus** [comment]
Alright, added a "DicePools" named range to Annika's character sheet in the requested format. It doesn't like the + that I put in the pool's string.
```
19:47:45.354 [Velen - Executor - 1] ERROR org.javacord.core.util.logging.ExceptionLoggerDelegateImpl - Caught unhandled exception!                                                                         
java.util.concurrent.CompletionException: `+` does not result in valid dice, or is not registered on the character sheet!
        at logic.RollLogic.rollDice(RollLogic.java:110) ~[TwoDee-7.1.3.jar:?]
        at logic.RollLogic.handleSlashCommandRoll(RollLogic.java:83) ~[TwoDee-7.1.3.jar:?]
        at logic.RollPoolLogic.lambda$onEvent$11(RollPoolLogic.java:96) ~[TwoDee-7.1.3.jar:?]
        at io.vavr.control.Try.onSuccess(Try.java:712) ~[vavr-0.10.4.jar:?]
        at logic.RollPoolLogic.onEvent(RollPoolLogic.java:96) ~[TwoDee-7.1.3.jar:?]
        at pw.mihou.velen.impl.VelenCommandImpl.runEvent(VelenCommandImpl.java:387) ~[Velen-2.1.1.jar:?]
        at pw.mihou.velen.impl.VelenCommandImpl.lambda$innerHandle$20(VelenCommandImpl.java:339) ~[Velen-2.1.1.jar:?]
        at pw.mihou.velen.ratelimiter.VelenRatelimiter.ratelimit(VelenRatelimiter.java:132) ~[Velen-2.1.1.jar:?]
        at pw.mihou.velen.impl.VelenCommandImpl.innerHandle(VelenCommandImpl.java:318) ~[Velen-2.1.1.jar:?]
        at pw.mihou.velen.impl.VelenCommandImpl.execute(VelenCommandImpl.java:185) ~[Velen-2.1.1.jar:?]
        at pw.mihou.velen.impl.VelenImpl.lambda$onSlashCommandCreate$12(VelenImpl.java:281) ~[Velen-2.1.1.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_72-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_72-internal]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_72-internal]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_72-internal]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]
Caused by: java.lang.IllegalArgumentException: `+` does not result in valid dice, or is not registered on the character sheet!
        at rolling.Roller.processPoolParam(Roller.java:101) ~[TwoDee-7.1.3.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_72-internal]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[?:1.8.0_72-internal]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) ~[?:1.8.0_72-internal]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471) ~[?:1.8.0_72-internal]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_72-internal]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_72-internal]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_72-internal]
        at rolling.Roller.lambda$parse$0(Roller.java:59) ~[TwoDee-7.1.3.jar:?]
        at io.vavr.control.Try.flatMapTry(Try.java:490) ~[vavr-0.10.4.jar:?]
        at io.vavr.control.Try.flatMap(Try.java:472) ~[vavr-0.10.4.jar:?]
        at rolling.Roller.parse(Roller.java:55) ~[TwoDee-7.1.3.jar:?]
        at logic.RollLogic.rollDice(RollLogic.java:103) ~[TwoDee-7.1.3.jar:?]
        ... 15 more
```

**Comment by belathus** [comment]
I went ahead and added the named range to Soma's character sheet.

**Comment by belathus** [comment]
Alright, added the `DicePool` named range to everyone's character sheet. Noticed, when testing, that the bot isn't parsing any pools that have more than one dice type, probably because I added a "+" character between different types of dice. However, pools of only a single type of dice (IE: 4d6) work just fine.
